/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AahaRouteImport } from './routes/aaha'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as CentreDetailsRouteImport } from './routes/centre-details'
import { Route as CentresRouteImport } from './routes/centres'
import { Route as CheckupRouteImport } from './routes/checkup'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyUploadsRouteImport } from './routes/my-uploads'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecommendedTestsRouteImport } from './routes/recommended-tests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeleconsultationRouteImport } from './routes/teleconsultation'
import { Route as TherapiesRouteImport } from './routes/therapies'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UploadFileRouteImport } from './routes/upload-file'
import { Route as UploadReportRouteImport } from './routes/upload-report'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as PrescriptionIdRouteImport } from './routes/prescription.$id'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ApiAdaptiveSplatRouteImport } from './routes/api/adaptive/$'
import { Route as DoctorConsultPatientIdRouteImport } from './routes/doctor.consult.$patientId'
import { Route as DoctorPrescriptionIdRouteImport } from './routes/doctor.prescription.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AahaRoute = AahaRouteImport.update({
  id: '/aaha',
  path: '/aaha',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreDetailsRoute = CentreDetailsRouteImport.update({
  id: '/centre-details',
  path: '/centre-details',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoute = CentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckupRoute = CheckupRouteImport.update({
  id: '/checkup',
  path: '/checkup',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyUploadsRoute = MyUploadsRouteImport.update({
  id: '/my-uploads',
  path: '/my-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedTestsRoute = RecommendedTestsRouteImport.update({
  id: '/recommended-tests',
  path: '/recommended-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeleconsultationRoute = TeleconsultationRouteImport.update({
  id: '/teleconsultation',
  path: '/teleconsultation',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapiesRoute = TherapiesRouteImport.update({
  id: '/therapies',
  path: '/therapies',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadFileRoute = UploadFileRouteImport.update({
  id: '/upload-file',
  path: '/upload-file',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadReportRoute = UploadReportRouteImport.update({
  id: '/upload-report',
  path: '/upload-report',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionIdRoute = PrescriptionIdRouteImport.update({
  id: '/prescription/$id',
  path: '/prescription/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdaptiveSplatRoute = ApiAdaptiveSplatRouteImport.update({
  id: '/api/adaptive/$',
  path: '/api/adaptive/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultPatientIdRoute = DoctorConsultPatientIdRouteImport.update({
  id: '/consult/$patientId',
  path: '/consult/$patientId',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPrescriptionIdRoute = DoctorPrescriptionIdRouteImport.update({
  id: '/prescription/$id',
  path: '/prescription/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aaha': typeof AahaRoute
  '/assessment': typeof AssessmentRoute
  '/centre-details': typeof CentreDetailsRoute
  '/centres': typeof CentresRoute
  '/checkup': typeof CheckupRoute
  '/consent': typeof ConsentRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/follow-up': typeof FollowUpRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/my-uploads': typeof MyUploadsRoute
  '/notifications': typeof NotificationsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommended-tests': typeof RecommendedTestsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teleconsultation': typeof TeleconsultationRoute
  '/therapies': typeof TherapiesRoute
  '/upload': typeof UploadRoute
  '/upload-file': typeof UploadFileRoute
  '/upload-report': typeof UploadReportRoute
  '/welcome': typeof WelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/report/$id': typeof ReportIdRoute
  '/api/adaptive/$': typeof ApiAdaptiveSplatRoute
  '/doctor/consult/$patientId': typeof DoctorConsultPatientIdRoute
  '/doctor/prescription/$id': typeof DoctorPrescriptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aaha': typeof AahaRoute
  '/assessment': typeof AssessmentRoute
  '/centre-details': typeof CentreDetailsRoute
  '/centres': typeof CentresRoute
  '/checkup': typeof CheckupRoute
  '/consent': typeof ConsentRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/follow-up': typeof FollowUpRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/my-uploads': typeof MyUploadsRoute
  '/notifications': typeof NotificationsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommended-tests': typeof RecommendedTestsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teleconsultation': typeof TeleconsultationRoute
  '/therapies': typeof TherapiesRoute
  '/upload': typeof UploadRoute
  '/upload-file': typeof UploadFileRoute
  '/upload-report': typeof UploadReportRoute
  '/welcome': typeof WelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/report/$id': typeof ReportIdRoute
  '/api/adaptive/$': typeof ApiAdaptiveSplatRoute
  '/doctor/consult/$patientId': typeof DoctorConsultPatientIdRoute
  '/doctor/prescription/$id': typeof DoctorPrescriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aaha': typeof AahaRoute
  '/assessment': typeof AssessmentRoute
  '/centre-details': typeof CentreDetailsRoute
  '/centres': typeof CentresRoute
  '/checkup': typeof CheckupRoute
  '/consent': typeof ConsentRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/follow-up': typeof FollowUpRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/my-uploads': typeof MyUploadsRoute
  '/notifications': typeof NotificationsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommended-tests': typeof RecommendedTestsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/screening': typeof ScreeningRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teleconsultation': typeof TeleconsultationRoute
  '/therapies': typeof TherapiesRoute
  '/upload': typeof UploadRoute
  '/upload-file': typeof UploadFileRoute
  '/upload-report': typeof UploadReportRoute
  '/welcome': typeof WelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/prescription/$id': typeof PrescriptionIdRoute
  '/report/$id': typeof ReportIdRoute
  '/api/adaptive/$': typeof ApiAdaptiveSplatRoute
  '/doctor/consult/$patientId': typeof DoctorConsultPatientIdRoute
  '/doctor/prescription/$id': typeof DoctorPrescriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aaha'
    | '/assessment'
    | '/centre-details'
    | '/centres'
    | '/checkup'
    | '/consent'
    | '/diagnostics'
    | '/doctor'
    | '/doctors'
    | '/emergency'
    | '/follow-up'
    | '/home'
    | '/journey'
    | '/language'
    | '/login'
    | '/my-uploads'
    | '/notifications'
    | '/prescriptions'
    | '/profile'
    | '/progress'
    | '/recommended-tests'
    | '/reports'
    | '/review'
    | '/screening'
    | '/services'
    | '/sitemap.xml'
    | '/teleconsultation'
    | '/therapies'
    | '/upload'
    | '/upload-file'
    | '/upload-report'
    | '/welcome'
    | '/api/chat'
    | '/prescription/$id'
    | '/report/$id'
    | '/api/adaptive/$'
    | '/doctor/consult/$patientId'
    | '/doctor/prescription/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aaha'
    | '/assessment'
    | '/centre-details'
    | '/centres'
    | '/checkup'
    | '/consent'
    | '/diagnostics'
    | '/doctor'
    | '/doctors'
    | '/emergency'
    | '/follow-up'
    | '/home'
    | '/journey'
    | '/language'
    | '/login'
    | '/my-uploads'
    | '/notifications'
    | '/prescriptions'
    | '/profile'
    | '/progress'
    | '/recommended-tests'
    | '/reports'
    | '/review'
    | '/screening'
    | '/services'
    | '/sitemap.xml'
    | '/teleconsultation'
    | '/therapies'
    | '/upload'
    | '/upload-file'
    | '/upload-report'
    | '/welcome'
    | '/api/chat'
    | '/prescription/$id'
    | '/report/$id'
    | '/api/adaptive/$'
    | '/doctor/consult/$patientId'
    | '/doctor/prescription/$id'
  id:
    | '__root__'
    | '/'
    | '/aaha'
    | '/assessment'
    | '/centre-details'
    | '/centres'
    | '/checkup'
    | '/consent'
    | '/diagnostics'
    | '/doctor'
    | '/doctors'
    | '/emergency'
    | '/follow-up'
    | '/home'
    | '/journey'
    | '/language'
    | '/login'
    | '/my-uploads'
    | '/notifications'
    | '/prescriptions'
    | '/profile'
    | '/progress'
    | '/recommended-tests'
    | '/reports'
    | '/review'
    | '/screening'
    | '/services'
    | '/sitemap.xml'
    | '/teleconsultation'
    | '/therapies'
    | '/upload'
    | '/upload-file'
    | '/upload-report'
    | '/welcome'
    | '/api/chat'
    | '/prescription/$id'
    | '/report/$id'
    | '/api/adaptive/$'
    | '/doctor/consult/$patientId'
    | '/doctor/prescription/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AahaRoute: typeof AahaRoute
  AssessmentRoute: typeof AssessmentRoute
  CentreDetailsRoute: typeof CentreDetailsRoute
  CentresRoute: typeof CentresRoute
  CheckupRoute: typeof CheckupRoute
  ConsentRoute: typeof ConsentRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  DoctorsRoute: typeof DoctorsRoute
  EmergencyRoute: typeof EmergencyRoute
  FollowUpRoute: typeof FollowUpRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  MyUploadsRoute: typeof MyUploadsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RecommendedTestsRoute: typeof RecommendedTestsRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  ScreeningRoute: typeof ScreeningRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeleconsultationRoute: typeof TeleconsultationRoute
  TherapiesRoute: typeof TherapiesRoute
  UploadRoute: typeof UploadRoute
  UploadFileRoute: typeof UploadFileRoute
  UploadReportRoute: typeof UploadReportRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiChatRoute: typeof ApiChatRoute
  PrescriptionIdRoute: typeof PrescriptionIdRoute
  ReportIdRoute: typeof ReportIdRoute
  ApiAdaptiveSplatRoute: typeof ApiAdaptiveSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aaha': {
      id: '/aaha'
      path: '/aaha'
      fullPath: '/aaha'
      preLoaderRoute: typeof AahaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre-details': {
      id: '/centre-details'
      path: '/centre-details'
      fullPath: '/centre-details'
      preLoaderRoute: typeof CentreDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres': {
      id: '/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof CentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkup': {
      id: '/checkup'
      path: '/checkup'
      fullPath: '/checkup'
      preLoaderRoute: typeof CheckupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-uploads': {
      id: '/my-uploads'
      path: '/my-uploads'
      fullPath: '/my-uploads'
      preLoaderRoute: typeof MyUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommended-tests': {
      id: '/recommended-tests'
      path: '/recommended-tests'
      fullPath: '/recommended-tests'
      preLoaderRoute: typeof RecommendedTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teleconsultation': {
      id: '/teleconsultation'
      path: '/teleconsultation'
      fullPath: '/teleconsultation'
      preLoaderRoute: typeof TeleconsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapies': {
      id: '/therapies'
      path: '/therapies'
      fullPath: '/therapies'
      preLoaderRoute: typeof TherapiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-file': {
      id: '/upload-file'
      path: '/upload-file'
      fullPath: '/upload-file'
      preLoaderRoute: typeof UploadFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-report': {
      id: '/upload-report'
      path: '/upload-report'
      fullPath: '/upload-report'
      preLoaderRoute: typeof UploadReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription/$id': {
      id: '/prescription/$id'
      path: '/prescription/$id'
      fullPath: '/prescription/$id'
      preLoaderRoute: typeof PrescriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adaptive/$': {
      id: '/api/adaptive/$'
      path: '/api/adaptive/$'
      fullPath: '/api/adaptive/$'
      preLoaderRoute: typeof ApiAdaptiveSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consult/$patientId': {
      id: '/doctor/consult/$patientId'
      path: '/consult/$patientId'
      fullPath: '/doctor/consult/$patientId'
      preLoaderRoute: typeof DoctorConsultPatientIdRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/prescription/$id': {
      id: '/doctor/prescription/$id'
      path: '/prescription/$id'
      fullPath: '/doctor/prescription/$id'
      preLoaderRoute: typeof DoctorPrescriptionIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorConsultPatientIdRoute: typeof DoctorConsultPatientIdRoute
  DoctorPrescriptionIdRoute: typeof DoctorPrescriptionIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorConsultPatientIdRoute: DoctorConsultPatientIdRoute,
  DoctorPrescriptionIdRoute: DoctorPrescriptionIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AahaRoute: AahaRoute,
  AssessmentRoute: AssessmentRoute,
  CentreDetailsRoute: CentreDetailsRoute,
  CentresRoute: CentresRoute,
  CheckupRoute: CheckupRoute,
  ConsentRoute: ConsentRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DoctorRoute: DoctorRouteWithChildren,
  DoctorsRoute: DoctorsRoute,
  EmergencyRoute: EmergencyRoute,
  FollowUpRoute: FollowUpRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  MyUploadsRoute: MyUploadsRoute,
  NotificationsRoute: NotificationsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RecommendedTestsRoute: RecommendedTestsRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  ScreeningRoute: ScreeningRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeleconsultationRoute: TeleconsultationRoute,
  TherapiesRoute: TherapiesRoute,
  UploadRoute: UploadRoute,
  UploadFileRoute: UploadFileRoute,
  UploadReportRoute: UploadReportRoute,
  WelcomeRoute: WelcomeRoute,
  ApiChatRoute: ApiChatRoute,
  PrescriptionIdRoute: PrescriptionIdRoute,
  ReportIdRoute: ReportIdRoute,
  ApiAdaptiveSplatRoute: ApiAdaptiveSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
